# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{skelerl}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ari Lerner", "Michael Fairchild", "Nate Murray"]
  s.date = %q{2009-08-18}
  s.description = %q{Erlang skeleton application}
  s.email = %q{arilerner@mac.com}
  s.executables = ["gen_server", "makefile", "skelerl", "skelerl-gen_server", "skelerl-makefile"]
  s.extra_rdoc_files = [
    "History.txt",
     "README.txt"
  ]
  s.files = [
    "Rakefile",
     "VERSION.yml",
     "bin/gen_server",
     "bin/makefile",
     "bin/skelerl",
     "bin/skelerl-gen_server",
     "bin/skelerl-makefile",
     "config/jeweler.rb",
     "config/requirements.rb",
     "generators/appfile/USAGE",
     "generators/appfile/appfile_generator.rb",
     "generators/appfile/templates/appfile.app",
     "generators/gen_server/USAGE",
     "generators/gen_server/gen_server_generator.rb",
     "generators/gen_server/templates/README.txt",
     "generators/gen_server/templates/Rakefile",
     "generators/gen_server/templates/gen_server.erl",
     "generators/gen_server/templates/gitignore",
     "generators/makefile/USAGE",
     "generators/makefile/makefile_generator.rb",
     "generators/makefile/templates/Emakefile",
     "generators/makefile/templates/Makefile",
     "generators/makefile/templates/appfile.app.erb",
     "generators/makefile/templates/make_boot.erl.erb",
     "generators/makefile/templates/start.sh",
     "generators/skeleton/USAGE",
     "generators/skeleton/skeleton_generator.rb",
     "generators/skeleton/templates/README.txt",
     "generators/skeleton/templates/Rakefile",
     "generators/skeleton/templates/gitignore",
     "script/generate",
     "tasks/build.rake",
     "tasks/environment.rake",
     "tasks/generate.rake",
     "tasks/website.rake"
  ]
  s.homepage = %q{http://poolpartyrb.com}
  s.rdoc_options = ["--quiet", "--title", "Skelerl documentation", "--line-numbers", "--main", "README"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{The most awesomenest erlang skeleton and generator!}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
